version: '3.9'

services:

  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=camps
